nohup: ignoring input
2025-09-24 10:58:03,205 - INFO - Starting MCPO Server...
2025-09-24 10:58:03,205 - INFO -   Name: MCP OpenAPI Proxy
2025-09-24 10:58:03,205 - INFO -   Version: 1.0
2025-09-24 10:58:03,205 - INFO -   Description: Automatically generated API from MCP Tool Schemas
2025-09-24 10:58:03,205 - INFO -   Hostname: openwebui
2025-09-24 10:58:03,205 - INFO -   Port: 9999
2025-09-24 10:58:03,205 - INFO -   API Key: Provided
2025-09-24 10:58:03,205 - INFO -   CORS Allowed Origins: ['*']
2025-09-24 10:58:03,205 - INFO -   Path Prefix: /
2025-09-24 10:58:03,205 - INFO - Configuring for a single StreamableHTTP MCP Server with URL http://127.0.0.1:8000/mcp
2025-09-24 10:58:03,205 - INFO - Uvicorn server starting...
INFO:     Started server process [3130224]
INFO:     Waiting for application startup.
2025-09-24 10:58:03,254 - INFO - HTTP Request: POST http://127.0.0.1:8000/mcp "HTTP/1.1 200 OK"
2025-09-24 10:58:03,254 - INFO - Received session ID: 41000d0da76040cc8cee97c7714ba6b6
2025-09-24 10:58:03,255 - INFO - Negotiated protocol version: 2025-06-18
2025-09-24 10:58:03,259 - INFO - HTTP Request: POST http://127.0.0.1:8000/mcp "HTTP/1.1 202 Accepted"
2025-09-24 10:58:03,260 - INFO - HTTP Request: GET http://127.0.0.1:8000/mcp "HTTP/1.1 200 OK"
2025-09-24 10:58:03,261 - INFO - HTTP Request: POST http://127.0.0.1:8000/mcp "HTTP/1.1 200 OK"
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 9999): address already in use
INFO:     Waiting for application shutdown.
2025-09-24 10:58:03,267 - INFO - HTTP Request: DELETE http://127.0.0.1:8000/mcp "HTTP/1.1 200 OK"
INFO:     Application shutdown complete.
2025-09-24 10:58:03,268 - INFO - Server shutdown complete
Starting MCP OpenAPI Proxy on 0.0.0.0:9999 with command: http://127.0.0.1:8000/mcp
2025-09-24 10:58:03,288 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<Server.serve() done, defined at /home/opc/mcpo/.venv/lib/python3.11/site-packages/uvicorn/server.py:69> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 164, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 1536, in create_server
    raise OSError(err.errno, msg) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 9999): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/typer/main.py", line 324, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/typer/core.py", line 694, in main
    return _main(
           ^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/typer/core.py", line 195, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/typer/main.py", line 699, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/mcpo/src/mcpo/__init__.py", line 126, in main
    asyncio.run(
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/home/opc/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 86, in _serve
    await self.startup(sockets=sockets)
  File "/home/opc/mcpo/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 174, in startup
    sys.exit(1)
SystemExit: 1
